apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jenkins
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.9.56

    helm:
      releaseName: jenkins

      values: |
        controller:
          serviceType: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true